export const browserCoreExamples = [
  "skynet browser status",
  "skynet browser start",
  "skynet browser stop",
  "skynet browser tabs",
  "skynet browser open https://example.com",
  "skynet browser focus abcd1234",
  "skynet browser close abcd1234",
  "skynet browser screenshot",
  "skynet browser screenshot --full-page",
  "skynet browser screenshot --ref 12",
  "skynet browser snapshot",
  "skynet browser snapshot --format aria --limit 200",
  "skynet browser snapshot --efficient",
  "skynet browser snapshot --labels",
];

export const browserActionExamples = [
  "skynet browser navigate https://example.com",
  "skynet browser resize 1280 720",
  "skynet browser click 12 --double",
  'skynet browser type 23 "hello" --submit',
  "skynet browser press Enter",
  "skynet browser hover 44",
  "skynet browser drag 10 11",
  "skynet browser select 9 OptionA OptionB",
  "skynet browser upload /tmp/skynet/uploads/file.pdf",
  'skynet browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "skynet browser dialog --accept",
  'skynet browser wait --text "Done"',
  "skynet browser evaluate --fn '(el) => el.textContent' --ref 7",
  "skynet browser console --level error",
  "skynet browser pdf",
];
